"""Natural-language explanation of pipeline results via Google Gemini."""

from __future__ import annotations

from typing import List, Optional

from ..config import LLM_CONFIG, require_google_api_key
from ..logging_utils import get_logger
from ..quantum.hardware import HardwareValidationResult
from ..quantum.vqe import VQEResult

logger = get_logger("explain")


def _get_model():
    import google.generativeai as genai

    genai.configure(api_key=require_google_api_key())
    model_name = LLM_CONFIG.get("model_name", "gemini-2.5-flash")
    return genai.GenerativeModel(model_name)


def explain_selection(
    top_molecules: List[VQEResult],
    scaffolds: List[str],
    functional_groups: List[str],
    hardware_result: Optional[HardwareValidationResult] = None,
    iterations: Optional[int] = None,
) -> str:
    """Ask Gemini to explain why these molecules were selected.

    Returns the model's plain-text response.  We deliberately *do not* let the
    LLM make claims about real-world drug efficacy.
    """
    if iterations is None:
        iterations = LLM_CONFIG.get("explanation_iterations", 3)

    molecule_block = "\n".join(
        f"- {r.smiles} (VQE energy: {r.energy:+.4f} Ha, {r.n_qubits} qubits)"
        for r in top_molecules
    )
    scaffold_block = ", ".join(scaffolds) if scaffolds else "none extracted"
    group_block = ", ".join(functional_groups) if functional_groups else "none extracted"

    if hardware_result and hardware_result.succeeded:
        hw_line = (
            f"Best molecule re-validated on Qiskit Aer: "
            f"{hardware_result.smiles} (energy: {hardware_result.energy:+.4f} Ha)"
        )
    else:
        hw_line = "Hardware validation step did not complete successfully."

    prompt = f"""
You are an AI assistant explaining the results of a quantum-guided molecular
discovery system.

Pipeline context
----------------
- Candidates were generated by a MolGAN (WGAN-GP) trained on a filtered
  ZINC small-molecule subset.
- Each candidate was scored by a Variational Quantum Eigensolver (VQE) on a
  PennyLane Lightning simulator using an STO-3G basis with an active-space
  approximation.
- A {iterations}-step feedback loop fine-tuned the MolGAN toward the lowest-
  energy candidates from each iteration.
- {hw_line}

Final selected molecules
------------------------
{molecule_block}

Common scaffolds across the top candidates: {scaffold_block}
Common functional groups across the top candidates: {group_block}

Task
----
Explain, in clear and concise scientific language suitable for a research
demo, why these molecules were selected.  Cover:
  1. What VQE energy means in this setting and why lower is preferred.
  2. Which structural patterns emerged across the top candidates.
  3. How the iterative MolGAN -> VQE -> feedback loop refined the population.
  4. Limitations of the current setup (active-space size, simulator-only,
     proof-of-concept generative model).

Constraints:
- Do NOT claim real-world drug efficacy or biological activity.
- Do NOT hallucinate clinical relevance.
- Stay under ~400 words.
""".strip()

    try:
        model = _get_model()
        response = model.generate_content(prompt)
        return response.text
    except Exception as exc:
        logger.error("Gemini call failed: %s", exc)
        return f"[Explanation unavailable: {exc}]"
