import os
import google.generativeai as genai

genai.configure(api_key="AIzaSyAI-tCA4WZwfHNpnrAa2F_CeaGaHctYK1E")

model = genai.GenerativeModel("gemini-2.5-flash")

def explain_selection(top_molecules, learned_features, iterations=3):

    molecule_text = "\n".join(
        [f"- {mol} (Quantum Score: {score:.4f})" for mol, score in top_molecules]
    )

    feature_text = ", ".join(learned_features)

    prompt = f"""
You are an AI assistant explaining the results of a quantum-guided
molecular discovery system.

Context:
- Molecules were generated by a classical model.
- Each molecule was evaluated using a quantum Variational Quantum
  Eigensolver (VQE), producing an energy-based fitness score.
- Lower (more negative) scores indicate more favorable candidates.
- The system iteratively learned common molecular features from
  high-performing molecules.

Optimization details:
- Iterations performed: {iterations}
- Learned favorable features: {feature_text}

Final selected molecules:
{molecule_text}

Task:
Explain, in clear and concise scientific language, why these molecules
were selected as the top candidates. Focus on:
- Quantum energy-based evaluation
- Learned structural patterns
- Iterative refinement process

Do NOT claim chemical efficacy or real-world drug validity.
Do NOT hallucinate biological effects.
Keep the explanation suitable for a hackathon demo.
"""

    response = model.generate_content(prompt)

    return response.text
